#!/usr/bin/ruby
require 'lib/Parser'
require 'lib/DSLLoader'
require 'lib/World'
require 'lib/CoreObjects'
require 'lib/ObjectManager'
require 'lib/Console'
require 'lib/SystemObject'

Backpack::World.new(Backpack::ObjectManager,Backpack::DSLLoader,Backpack::Console,Parser::Parser).go
