#!/usr/bin/ruby
require 'lib/Parser'
require 'lib/DSLLoader'
require 'lib/World'
require 'lib/CoreObjects'
require 'lib/ObjectManager'
require 'lib/Console'
require 'lib/SystemObject'
logger = Logger.new(STDOUT)
logger.level = Logger::INFO
Parser.logger = logger
Backpack.logger = logger
Backpack::World.new(Backpack::ObjectManager,Backpack::DSLLoader,Backpack::Console,Parser).start_world
