#!/usr/bin/ruby
require 'lib/Parser'
require 'lib/DSLLoader'
require 'lib/World'
require 'lib/CoreObjects'
require 'lib/RoomManager'
require 'lib/Console'

Backpack::World.new(Backpack::RoomManager,Backpack::DSLLoader).go
